# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/salaa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),salaa)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,33b72205cc7f75993ae4186b0b5f966c3addb134)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,2f68cd9f5e92a199d17e5f81bd4cf02ce258ae27)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,329527bd1265a4d4fb9a9ee6475c47c1873ad73f)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,2e772d1c0e5727ac00a95479e9b3e269e9dfd5c4)
$(call add-radio-file-sha1-checked,radio/cdt_engineering.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/gz.img,33e3013e6ae32e60d4d1419c61263007083c4353)
$(call add-radio-file-sha1-checked,radio/lk.img,c3be41982f92bb7e7cc3397c4ff8959c1734c4ac)
$(call add-radio-file-sha1-checked,radio/logo.bin,99cf49cf912db8e1503ccfa107c6ad4882a3516e)
$(call add-radio-file-sha1-checked,radio/md1img.img,e1c69185ab81151a2b9a530d35c089a23289a5fa)
$(call add-radio-file-sha1-checked,radio/preloader_ufs.img,c39637205f4a216f1f545154555909803eba4c9b)
$(call add-radio-file-sha1-checked,radio/scp.img,a4ec533471e3d180550f07ce924664c310f94e46)
$(call add-radio-file-sha1-checked,radio/spmfw.img,42e298648c546dab0de554f6159b42203e679fd2)
$(call add-radio-file-sha1-checked,radio/sspm.img,d64aec58746ad6d38e3cccfc6d6421612cef950d)
$(call add-radio-file-sha1-checked,radio/tee.img,3477800631eea75dbc2bbd10321f30a621c3870b)

endif
